###
POST http://localhost:8080/hogwarts/faculty/
Content-Type: application/json

{
  "name"  : "Gryffindor",
  "color" : "red"
}

###
POST http://localhost:8080/hogwarts/faculty/
Content-Type: application/json

{
  "name"  : "Hufflepuff",
  "color" : "yellow"
}

###
PUT http://localhost:8080/hogwarts/faculty/
Content-Type: application/json

{
  "id"    : 2,
  "name"  : "Gryffindor",
  "color" : "gold"
}
###
PUT http://localhost:8080/hogwarts/faculty/
Content-Type: application/json

{
  "id"    : 10,
  "name"  : "Gryffindor",
  "color" : "green"
}

###
DELETE http://localhost:8080/hogwarts/faculty/2
###
GET http://localhost:8080/hogwarts/faculty/all
###
GET http://localhost:8080/hogwarts/faculty/0
###
GET http://localhost:8080/hogwarts/faculty?color=red
###
GET http://localhost:8080/hogwarts/faculty?color=yellow
###
GET http://localhost:8080/hogwarts/faculty?color=gold


