###
POST http://localhost:8080/hogwarts/student/
Content-Type: application/json

{
  "name": "Sergei",
  "age": 46
}

###
POST http://localhost:8080/hogwarts/student/
Content-Type: application/json

{
  "name": "Mark Twain-3",
  "age": 187,
  "faculty": 4
}

###
PUT http://localhost:8080/hogwarts/student/
Content-Type: application/json

{
  "id"    : 1,
  "name"  : "Sergei",
  "age"   : 47,
  "faculty": 3
}

###
PUT http://localhost:8080/hogwarts/student/
Content-Type: application/json

{
  "id"    : 4,
  "name"  : "Mark Twain",
  "age"   : 187,
  "faculties_id" : 4
}
###
DELETE http://localhost:8080/hogwarts/student/1
###
GET http://localhost:8080/hogwarts/student/all
###
GET http://localhost:8080/hogwarts/student/1
###
GET http://localhost:8080/hogwarts/student?age=461
###
GET http://localhost:8080/hogwarts/student?age=46
###
GET http://localhost:8080/hogwarts/student?age0=45&age1=46
###
GET http://localhost:8080/hogwarts/student?age0=46&age1=46
###
GET http://localhost:8080/hogwarts/student?age0=46&age1=47
###
GET http://localhost:8080/hogwarts/student?age0=46&age1=158
###
GET http://localhost:8080/hogwarts/student?age0=47&age1=158

### Get Faculty by Student id=3
GET http://localhost:8080/hogwarts/student/3/faculty
### Get Faculty by Student id=1
GET http://localhost:8080/hogwarts/student/1/faculty


