###
GET http://localhost:8080/hogwarts/student/1/avatar
### ALTERNATIVE Get Avatar (Student 1)
GET http://localhost:8080/hogwarts/student/1/avatar/alter-avatar
###
GET http://localhost:8080/hogwarts/student/1/avatar/preview
### ALTERNATIVE Get Preview (Student 1)
GET http://localhost:8080/hogwarts/student/1/avatar/alter-preview
###
GET http://localhost:8080/hogwarts/student/2/avatar
###
GET http://localhost:8080/hogwarts/student/2/avatar/preview
###
GET http://localhost:8080/hogwarts/student/4/avatar
###
GET http://localhost:8080/hogwarts/student/4/avatar/preview
###
GET http://localhost:8080/hogwarts/student/14/avatar
### ALTERNATIVE Get Avatar (Student 14)
GET http://localhost:8080/hogwarts/student/14/avatar/alter-avatar
###
GET http://localhost:8080/hogwarts/student/14/avatar/preview
### ALTERNATIVE Get Preview (Student 14)
GET http://localhost:8080/hogwarts/student/14/avatar/alter-preview

### Upload Avatar StudentId=1
POST http://localhost:8080/hogwarts/student/1/avatar
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="avatar"; filename="E6A899EC-5E9D-409B-9ECA-F0B45C69EDFD.Small.jpg"
Content-Type: image/jpeg

< ../data/client-upload-dir/E6A899EC-5E9D-409B-9ECA-F0B45C69EDFD.Small.jpg
--WebAppBoundary

### Upload alternative Avatar StudentId=1
POST http://localhost:8080/hogwarts/student/1/avatar
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="avatar"; filename="IMG_6009.YachtClub.JPG"
Content-Type: image/jpeg

< ../data/client-upload-dir/IMG_6009.YachtClub.JPG
--WebAppBoundary

### Upload Avatar for Harry Potter
POST http://localhost:8080/hogwarts/student/2/avatar
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="avatar"; filename="images-harry-potter-order-phoenix-5.jpeg"
Content-Type: image/jpeg

< ../data/client-upload-dir/images-harry-potter-order-phoenix-5.jpeg
--WebAppBoundary